# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PointsRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PointsRN

  pod "GoogleSignIn"
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'PointsRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PointsRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PointsRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PointsRN-tvOS

end
